### ISSUE TITLE
BACKEND - news update page not inserting properly

### ISSUE THREAD

**Issue by samsitconsulting** [kozmacm/responsiveFishy#10]
Need to add to the if statement to account for no image being selected.

**Comment by samsitconsulting** [comment]
modified the outer if statement to account for no images being selected.

**Comment by samsitconsulting** [comment]
Added new folder in the img directory to hold the files being uploaded.

**Comment by samsitconsulting** [comment]
Currently works as needed but will leave issue open to add to it.

**Comment by kozmacm** [comment]
As far as I can tell, and I have tried multiple times, a database entry is still not created if there is no image added to the news post.

**Comment by kozmacm** [comment]
Fixed. Works as expected now.
