### ISSUE TITLE
FRONTEND - need to add christmas theme

### ISSUE THREAD

**Issue by samsitconsulting** [kozmacm/responsiveFishy#4]
Need to add christmas theme to the site for the holidays.

**Comment by kozmacm** [comment]
I responded via email also, but this is a great idea and I thought it looked great on the old site. Possibly change theme colors and/or add Christmas lights?

**Comment by samsitconsulting** [comment]
Need to resize the old jpg to fit the responsive site for the christmas theme.

**Comment by samsitconsulting** [comment]
I added snowflakes on the index page and will add more tomorrow.
