### ISSUE TITLE
SUPPORT - Add email domains to phones

### ISSUE THREAD

**Issue by samsitconsulting** [kozmacm/responsiveFishy#6]
We need to add #####@fishybusinesssc.com to Owners phones and PC for tracking.  We also might want to forward it to their personal emails if needed.

**Comment by kozmacm** [comment]
Good idea. Currently I have the 'contact us' page emailing to support@fishybusinesssc.com and have already created this email account. We can change any of that if necessary.

**Comment by kozmacm** [comment]
Currently we are forwarding these emails to Sam and I and then one of us has to forward to Chuck or Guy. Need to email one of those two and figure out who needs this email added to their phone and go up there and do it for them. Godaddy provides an easy way to do this on any type of phone now. Also possibly need to set up the computer in the office or the computer by the cash register to get these emails just in case typing on a phone is inconvenient on a given day.

**Comment by kozmacm** [comment]
We have added support@fishybusinesssc.com to Guy and Chuck's phones. Did this over a month ago.
